CREATE TABLE ADM00.EMPLOYEE (
 	ID VARCHAR(32)  ,
 	NAME VARCHAR(32),
 	SALARY NUMBER(22,4),
 	DEPARTMENTID VARCHAR(8)
);

CREATE TABLE ADM00.DEPARTMENT (
 	ID VARCHAR(32)  ,
 	NAME VARCHAR(32)
);

GRANT ALL ON ADM00.EMPLOYEE TO APP1;
GRANT ALL ON ADM00.DEPARTMENT TO APP1;



SELECT d.name, T1.NAME , T1.SALARY
FROM (
	SELECT e.ID , e.NAME , e.SALARY , e.DEPARTMENTID, DENSE_RANK () OVER(PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) RN 
	FROM EMPLOYEE e 
) T1
LEFT JOIN DEPARTMENT d ON T1.DEPARTMENTID = d.ID 
WHERE T1.RN <= 3;
